language: python
python:
  - '3.6'
  - '3.7'
  - '3.8'
  - 'pypy3'

install:
  - pip install -r requirements/tasks.txt
  - pip-sync requirements/development.txt
  - pip install -e .

script:
  - flake8 pyfat tests
  - py.test --cov=pyfat tests

after_success:
  - coveralls
